name: Deploy API

on:
  workflow_run:
    workflows: ["CI/CD - NestJS"]
    types:
      - completed
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-render:
    name: Deploy to Render
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Render
        if: ${{ secrets.RENDER_SERVICE_ID != '' && secrets.RENDER_API_KEY != '' }}
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}

  deploy-railway:
    name: Deploy to Railway
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Railway
        if: ${{ secrets.RAILWAY_TOKEN != '' }}
        uses: bervProject/railway-deploy@v1.1.9
        with:
          railway_token: ${{ secrets.RAILWAY_TOKEN }}
          service: ${{ secrets.RAILWAY_SERVICE_NAME || 'stick-note-api' }}

  verify-deployment:
    name: Verify Deployment
    runs-on: ubuntu-latest
    needs: [deploy-render, deploy-railway]
    if: always()
    steps:
      - name: Wait for deployment
        run: sleep 30

      - name: Check Render deployment
        if: ${{ secrets.RENDER_SERVICE_URL != '' }}
        run: |
          curl -f ${{ secrets.RENDER_SERVICE_URL }}/health || echo "Render deployment check failed"

      - name: Check Railway deployment  
        if: ${{ secrets.RAILWAY_SERVICE_URL != '' }}
        run: |
          curl -f ${{ secrets.RAILWAY_SERVICE_URL }}/health || echo "Railway deployment check failed"